# docker image.
image: prod-registry-to-be-replaced/spring-simple:latest

# replicas.
replicas: 10

# resources.
resources:
  requests:
    cpu: 2000m
    memory: 5Gi
  limits:
    cpu: 2000m
    memory: 5Gi

# affinity.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-type
              operator: In
              values:
                - "worker"

# tolerations.
tolerations: {}

# hpa.
hpa:
  enabled: true
  minReplicas: 10
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50

# spring profile.
spring:
  profiles:
    active: prod

# java opts.
javaOpts: "-Xms4G -Xmx4G"

# ingress.
ingress:
  enabled: true
  ingressClassName: nginx
  hostName: spring-simple.cloudchef-labs.com
  path: /
